/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-08-29 06:38:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ddd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.4.1.jar", Long.valueOf(1503538031168L));
    _jspx_dependants.put("jar:file:/E:/test/habernateTest/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/QingFeng/WEB-INF/lib/struts2-core-2.3.4.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1343981466000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<title>员工管理</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\" href=\"js/jquery-easyui-1.5.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\" href=\"js/jquery-easyui-1.5.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-easyui-1.5.2/jquery.easyui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#cc\").datagrid({\r\n");
      out.write("\t\t\turl:\"renmenzy\",\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tidField : \"id\",\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpageSize : 20,\r\n");
      out.write("\t\t\tpageList : [10, 20, 30, 40],\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tsortName : \"id\",\r\n");
      out.write("\t\t\tsortOrder : \"desc\",\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){    \r\n");
      out.write("\t\t        $(\"a[name='opera']\").linkbutton({text:'修改',plain:true,iconCls:'icon-edit'});\r\n");
      out.write("\t\t        $(\"a[name='oo']\").linkbutton({text:'删除',plain:true,iconCls:'icon-remove'});  \r\n");
      out.write("\t\t\t\t}, \r\n");
      out.write("\t\t\tcolumns : [[   \r\n");
      out.write("\t\t\t\t\t{field : \"list.hm_id\",title:\"编号\",width : 70,sortable :true},\r\n");
      out.write("\t\t\t           {field : \"list.hm_title\",title:\"标题\",width:70,sortable :true},\r\n");
      out.write("\t\t\t           {field : \"list.hm_picture\",title:\"图片\",width:70,sortable:true},\r\n");
      out.write("\t\t\t           {field : \"list.hm_content\",title:\"内容\",width:70,sortable:true},\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tfield:'operate',field:'operate',title:'操作',align:'center',formatter : delectId, width:$(this).width()*0.1,   \r\n");
      out.write("\t\t\t\t\t\tformatter:function(value, row, index){ \r\n");
      out.write("\t\t\t\t\t        var str = '<a href=\"#\" onclick=\"editUser('+index+')\" name=\"opera\" class=\"easyui-linkbutton\" ></a>';  \r\n");
      out.write("\t\t\t\t\t        var ss = '<a href=\"#\" onclick=\"delect('+index+')\"name=\"oo\" class=\"easyui-linkbutton\" ></a>';\r\n");
      out.write("\t\t\t\t\t        return str+ss;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t     ]],\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doRow(){\r\n");
      out.write("\t\talert(\"ttt\");\r\n");
      out.write("\t\tvar row = $('#cc').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\talert('ID:'+row.a_id+\" 学校名称:\"+row.u_name);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*-------------------------------------------------------------------------------*/\r\n");
      out.write("\tfunction delectId(val,row,index){\r\n");
      out.write("\t\treturn '&nbsp;&nbsp;<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:\"icon-remove\"\" onclick=\"editUser('+index+')\">编辑</a>'+'&nbsp;&nbsp;<a href=\"#\" onclick=\"delect('+index+')\">删除</a>';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction editUser(index){\t\t//修改方法\r\n");
      out.write("\t\t $('#cc').datagrid('selectRow',index);// 关键在这里\r\n");
      out.write("\t\t\tvar row = $('#cc').datagrid('getSelected');\r\n");
      out.write("\t\t $('#u_name').val(row.u_name);\r\n");
      out.write("\t\t $('#u_seq').val(row.u_seq);\r\n");
      out.write("\t\t $('#u_description').val(row.u_description);\r\n");
      out.write("\t\t $('#u_state').val(row.u_state);\r\n");
      out.write("\t\t $('#u_id').val(row.u_id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$('#dlg').dialog('open')\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delect(index){\t\t//删除方法\r\n");
      out.write("\t\t$('#cc').datagrid('selectRow',index);// 关键在这里\r\n");
      out.write("\t\tvar row = $('#cc').datagrid('getSelected');\r\n");
      out.write("\t\talert('确认删除该角色信息?');\r\n");
      out.write("\t\tvar u_id = row.u_id;\r\n");
      out.write("\t\twindow.location.href =\"Delete_user.action?u_id=\"+u_id;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*--------------------------点击按钮取值--------------------------------*/\r\n");
      out.write("\tfunction getSelected(){\r\n");
      out.write("\t\tvar row = $('#cc').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\talert('ID:'+row.a_id+\" 角色名称:\"+row.u_name);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getSelections(){\r\n");
      out.write("\t\tvar ids = [];\r\n");
      out.write("\t\tvar rows = $('#cc').datagrid('getSelections');\r\n");
      out.write("\t\tfor(var i=0; i<rows.length; i++){\r\n");
      out.write("\t\t\tids.push(rows[i].itemid);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\talert(ids.join('\\n'));\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* --------新增----------------------------------------------------------------------- */\r\n");
      out.write("function Add(){\r\n");
      out.write("\t$('#add_dlg').dialog('open')  //打开添加窗口\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"ss\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("<div data-options=\"region:'north',title:'管理中心：',split:true,plain:true,iconCls:'icon-remove'\" style=\"height:150px\" >\r\n");
      out.write("<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-remove'\"  onclick=\"alert('vfss')\">新增</a>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<div data-options=\"region:'west',title:'树状列表：',split:true\" style=\"width:200px\"></div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"center\" data-options=\"region:'center' ,title:'角色信息：',split:true\"  style=\"padding:5px;background:#eee\">\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true\">  \r\n");
      out.write("\t\t<div  data-options=\"region:'north',title:'表格信息' \" style=\"height:60px\" >\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"plain:true,iconCls:'icon-add'\"  onclick=\"Add()\">新增</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div data-options=\"region:'center',title:'南方：' \" >\r\n");
      out.write("\t\t\t<div class=\"easyui-tabs\" fit=\"true\" style=\"height:250px,width:300px\" >\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table id=\"cc\" class=\"easyui-datagrid\" pagination=\"true\"></table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<div id=\"dlg\" class=\"easyui-dialog\" title=\"修改\"\r\n");
      out.write("\t\tstyle=\"width: 80%; height: 300px; max-width: 300px; padding: 2px; display: none;\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'保存',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#dlg').dialog('close')  //关闭修改窗口\r\n");
      out.write("\t\t\t\t\t\talert('修改成功!');\r\n");
      out.write("\t\t\t\t\t\tdocument.edit_form.submit();   //提交修改form表单\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-no',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#dlg').dialog('close')  //关闭修改窗口\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form name=\"edit_form\" action=\"Edit_user\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">角色名称：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"u_name\"  name=\"user.u_name\" class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">排序号：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"u_seq\"  name=\"user.u_seq\"  class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">状态：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"u_state\"  name=\"user.u_state\"   class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">描述：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"u_description\"  name=\"user.u_description\"   class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- 隐藏域保存ID主键 -->\r\n");
      out.write("\t\t\t\t<td><input type=\"hidden\" id=\"u_id\"  name=\"user.u_id\"  class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- -----添加窗口----------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"add_dlg\" class=\"easyui-dialog\" title=\"添加院校\"\r\n");
      out.write("\t\tstyle=\"width: 80%; height: 300px; max-width: 300px; padding: 2px; display: none;\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'添加',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('修改成功！');\r\n");
      out.write("\t\t\t\t\t\tdocument.add_form.submit();   //提交添加form表单\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-no',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#add_dlg').dialog('close')  //关闭添加窗口\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form name=\"add_form\" action=\"Save_user\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">角色名称：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\"  name=\"user.u_name\" class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">排序：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\"  name=\"user.u_seq\"  class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">状态：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\"   name=\"user.u_state\"   class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label class=\"la\">描述：</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\"   name=\"user.u_description\"   class=\"ct\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
