/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-09-21 12:02:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.houtai;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class zhaosheng_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>&nbsp;清风教育网 - 招生简章</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../script/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../script/jquery-easyui-1.5.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../script/jquery-easyui-1.5.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../script/jquery-easyui-1.5.2/jquery.easyui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../script/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:30px auto;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t\r\n");
      out.write("\tcolor:#666;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin:10px;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\tcolor:#F30;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("\tletter-spacing:5px;\r\n");
      out.write("\tfont-weight:600;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("\tfont-size:13px;\r\n");
      out.write("}\r\n");
      out.write("tr {\r\n");
      out.write("\theight:50px;\r\n");
      out.write("}\r\n");
      out.write("tr:nth-of-type(odd) {\r\n");
      out.write("\tbackground-color:#FFF;\r\n");
      out.write("}\r\n");
      out.write("tr:nth-of-type(even) {\r\n");
      out.write("\tbackground-color:#F2F2F2;\r\n");
      out.write("}\r\n");
      out.write("tr:hover {\r\n");
      out.write("\tcolor:#F30;\r\n");
      out.write("\tbackground-color:#EFFEED;\r\n");
      out.write("}\r\n");
      out.write("tr:hover td:nth-child(1){\r\n");
      out.write("\tbackground:url(images/tr-hover-bg.png) no-repeat 3px 8px;\r\n");
      out.write("}\r\n");
      out.write("th {\r\n");
      out.write("\tborder-bottom:1px solid #CCC;\r\n");
      out.write("\tborder-top:1px solid #CCC;\r\n");
      out.write("\tcolor:#333;\r\n");
      out.write("\tbackground-color:#F8F4DA;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("\tborder-bottom:1px solid #CCC;\r\n");
      out.write("}\r\n");
      out.write("/*定义列的宽度*/\r\n");
      out.write("[id^=\"Im\"] {\r\n");
      out.write("\twidth:500px;\r\n");
      out.write("}\r\n");
      out.write("[id=\"ImTx\"] {\r\n");
      out.write("\twidth:510px;\r\n");
      out.write("}\r\n");
      out.write("[id=\"Gxw\"] {\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write("[id=\"Xtt\"] {\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"SetUp\"] {\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write(".dc{\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("[id=\"ld\"] {\r\n");
      out.write("\ttext-indent:3px;\r\n");
      out.write("\tfont:\"楷体\";\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tbackground: rgba(255,255,255,0.1) no-repeat;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid gray;\r\n");
      out.write("\tletter-spacing:3px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#ld:hover{\r\n");
      out.write("\tletter-spacing:2px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("\tbackground-color:rgba(255,255,255,0.5);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".la{\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tmargin:10px;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\tcolor:#F30;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("\tletter-spacing:5px;\r\n");
      out.write("\tfont-weight:600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ct{\r\n");
      out.write("\twidth:350px;\r\n");
      out.write("\theight:28px;\r\n");
      out.write("\tfont-size:24px;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("\tbackground:rgba(255,255,255,0.5); \r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid #0492d6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cz{\r\n");
      out.write("\twidth: 95%; \r\n");
      out.write("\theight: 230px; \r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tfont-family:'楷体'; \r\n");
      out.write("\tborder-radius: 5px; \r\n");
      out.write("\tborder: 0.2; \r\n");
      out.write("\tcolor: red; \r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, .05);\r\n");
      out.write("\tfont:'楷体';\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("}\r\n");
      out.write(".report-file {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    height: 28px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border: 1px solid #428bca;\r\n");
      out.write("    background: none repeat scroll 0 0 #428bca;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write(".report-file span {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: block;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("}\r\n");
      out.write(".file-prew {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left:0;\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    font-size: 100px; \r\n");
      out.write("    opacity: 0; \r\n");
      out.write("    filter: alpha(opacity=0);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("td:hover{\r\n");
      out.write("\ttext-overflow:inherit;\r\n");
      out.write("\toverflow:visible;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#xg1\").click(function(){\r\n");
      out.write("\t\t\ttextName1.value = $(\"#zs1\").text();\r\n");
      out.write("\t\t\ttextName2.value = $(\"#zs3\").text();\r\n");
      out.write("\t\t\ttextName3.value = $(\"#zs5\").text();\r\n");
      out.write("\t\t\ttextName4.value = $(\"#zs6\").text();\r\n");
      out.write("\t\t\tjj.value = $(\"#zs2\").text();\r\n");
      out.write("\t\t\tnr.value = $(\"#zs4\").text();\r\n");
      out.write("\t\t\tlx.value = $(\"#zs7\").text();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#xz\").click(function(){\r\n");
      out.write("\t\t\t/*新增*/\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" title=\"修改\"\r\n");
      out.write("\t\tstyle=\"width: 80%; height: 400px; max-width: 800px; padding: 2px; display: none;\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'确定',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ccwjcg',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('ok');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ccwjsb',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('cancel');;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>图标</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName1').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName1\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>院校图片</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName2').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName2\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>专业图片</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName3').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName3\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>毕业证图片</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName4').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName4\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label class=\"la\">学校简介：</label><textarea rows=\"10\" cols=\"20\" id=\"jj\" class=\"cz\" ></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<label class=\"la\">介绍内容：</label><textarea rows=\"10\" cols=\"20\" id=\"nr\" class=\"cz\" ></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label class=\"la\">类型：</label><input type=\"text\" id=\"lx\" class=\"ct\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t\t首页新闻管理\r\n");
      out.write("\t\t<div style=\"float:right\">\r\n");
      out.write("\t\t\t<label title=\"新增数据\">\r\n");
      out.write("\t\t\t\t<a type=\"radio\" id=\"xz\" href=\"javascript:void(0)\" onclick=\"$('#dlg').dialog('open')\"\r\n");
      out.write("\t\t\t\t class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\">\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t<img src=\"../images/png/xzsj.png\" style=\"width:25px;height:25px;top:2px;\" />新增\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<th id=\"Gxw\">图标</th>\r\n");
      out.write("\t\t\t<th id=\"Gxw\">学校简介</th>\r\n");
      out.write("\t\t\t<th id=\"Gxw\">院校图片</th>\r\n");
      out.write("\t\t\t<th id=\"Gxw\">介绍内容</th>\r\n");
      out.write("\t\t\t<th id=\"Xtt\">专业图片</th>\r\n");
      out.write("\t\t\t<th id=\"Xtt\">毕业证图片</th>\r\n");
      out.write("\t\t\t<th id=\"Xtt\">类型</th>\r\n");
      out.write("\t\t\t<th id=\"SetUp\">操作</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td id=\"zs1\">s1.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs2\">江西农业大学是一所以农为优势、以生物技术为特色、多学科协调发展的有特色高水平大学；具有博士学位授予权；是我国首批具有学士学位、硕士学位授予权单位之一；是江西省最早开展研究生教育的高校；是农业部与江西省人民政府共建高校，是国家林业局与江西省人民政府共建高校；国家“中西部高校基础能力建设工程”高校。</td>\r\n");
      out.write("\t\t\t<td id=\"zs3\">school.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs4\">江西农业大学是一所以农为优势、以生物技术为特色、多学科协调发展的有特色高水平大学；具有博士学位授予权；是我国首批具有学士学位、硕士学位授予权单位之一；是江西省最早开展研究生教育的高校；是农业部与江西省人民政府共建高校，是国家林业局与江西省人民政府共建高校；国家“中西部高校基础能力建设工程”高校。学校位于南昌经济技术开发区，总占地面积1.6万亩。校园风景秀丽，景色宜人。 学校溯源于1905年创办的江西实业学堂，1908年更名为江西高等农业学堂。本科教育肇始于1940年创办的国立中正大学，1949年更名为南昌大学，1952年组建江西农学院。1958年创办江西共产主义劳动大学总校，1968年更名为江西共产主义劳动大学。1969年江西农学院和江西共产主义劳动大学合并。1980年11月更名为江西农业大学。 学校育人体系完备。学科涵盖农、理、工、经、管、文、法、教、哲、艺等10大门类。现设有17个学院，各类全日制在校学生达26000余人（含独立学院）。有3个一级学科博士点，19个一级学科硕士点，68个本科专业。有1个国家林业局重点学科，3个江西省高水平学科，7个省级重点学科。有1个国家二类特色专业，4个国家一类特色专业，9个省级特色专业。有2个博士后科研流动站，1个博士后科研工作站。2014年，招收了江西省第一个外籍博士后。 学校师资力量雄厚。现有在职教职工近1600余人，其中具有博士、硕士学位人员占教师总数的80%以上。有中国科学院院士1人，“国家杰出青年基金”获得者2人，国家“万人计划”领军人才3人，国家中青年科技创新领军人才1人。有全国“五四”奖章获得者2人，国家级有突出贡献中青年专家3人，国家“百千万人才工程”人选5人，“中国青年科技奖”获得者3人，国家现代农业产业技术体系岗位科学家3人，教育部“新世纪优秀人才支持计划”人选4人，“赣鄱英才555工程”人选24人。有“全国杰出专业技术人才先进集体”、教育部“长江学者和创新团队发展计划”</td>\r\n");
      out.write("\t\t\t<td id=\"zs5\">zy.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs6\">byz.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs7\">江西农业大学</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<label title=\"修改信息\"> \r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg1\" href=\"javascript:void(0)\" onclick=\"$('#dlg').dialog('open')\">\r\n");
      out.write("\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/png/xg.png\" style=\"width:15px;height:15px;\" />\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t修改\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t<label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\">\r\n");
      out.write("\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/png/sc.png\" style=\"width:15px;height:15px;\" />\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t删除\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td id=\"zs1\">s2.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs2\">北京外国语大学，简称北外，由中华人民共和国教育部直属，位列国家首批“211工程”，入选“985工程优势学科创新平台”、\"2011计划\"</td>\r\n");
      out.write("\t\t\t<td id=\"zs3\">school.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs4\">北京外国语大学（Beijing Foreign Studies University），简称北外，由中华人民共和国教育部直属，位列国家首批“211工程”，入选“985工程优势学科创新平台”、“2011计划”，为财政部6所“小规模试点高校“之一，国际大学翻译学院联合会成员，设有研究生院，是中国外国语类高等院校中历史悠久、教授语种最多、办学层次齐全的全国重点大学，被誉为“共和国外交官摇篮”。 北京外国语大学前身是1941年成立于延安的中国人民抗日军事政治大学三分校俄文大队，后发展为延安外国语学校，建校始隶属于中国共产党领导。新中国成立后，学校归外交部领导。1954年，更名为北京外国语学院；1959年，与北京俄语学院合并组建新的北京外国语学院。1980年后直属国家教育部领导。1994年，正式更名为北京外国语大学。</td>\r\n");
      out.write("\t\t\t<td id=\"zs5\">zy.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs6\">byz.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs7\">北京大学</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<label title=\"修改信息\"> \r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg1\" href=\"javascript:void(0)\" onclick=\"$('#dlg').dialog('open')\">\r\n");
      out.write("\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/png/xg.png\" style=\"width:15px;height:15px;\" />\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t修改\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t<label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\">\r\n");
      out.write("\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/png/sc.png\" style=\"width:15px;height:15px;\" />\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t删除\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td id=\"zs1\">s2.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs2\">赣南师范大学位于国家历史文化名城、江西省域副中心城市——赣州市。</td>\r\n");
      out.write("\t\t\t<td id=\"zs3\">school.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs4\">赣南师范大学位于国家历史文化名城、江西省域副中心城市——赣州市。学校创办于1958年6月，时为赣南师范专科学校；1984年更名为赣南师范学院，升格为省属本科师范院校；2003年成为硕士学位授予权单位，是赣粤闽湘四省边际区域唯一具有硕士学位授予权的省属本科师范院校。2016年3月，学校经教育部批准更名为赣南师范大学。 学校现有黄金校区、章贡校区、白塔校区（大学科技园）3个校区，占地2200余亩，校舍建筑面积80余万平方米，教学科研仪器设备总值2.2亿余元，图书馆藏书220余万册。设有19个教学学院、1所独立学院和1所附属中学，有涵盖10个学科门类的71个本科专业、9个一级学科硕士点（涵盖62个二级学科硕士点）和5个硕士专业学位授权点。面向全国27个省（区、市）招生，现有全日制在校生19000余人，其中研究生近1200人。 学校现有专任教师近1000人，其中高级专业技术人员430余人，博士教师230余人；近年来引进和培养了一批学科学术领军人才，现有中国工程院双聘院士1人，有国家新世纪百千万人才工程人选、教育部新世纪优秀人才计划人选、国务院特殊津贴专家等20余人，教师队伍的学历结构、职称结构、学缘结构得到明显优化。广大教师爱岗敬业、教书育人，涌现了“全国优秀教师”“全国优秀科技工作者”“全球孔子学院先进个人”“江西省五一劳动奖章”“江西省教育系统师德标兵”等一批先进典型。 学校始终坚持人才培养中心地位，2014年荣获2项国家教学成果奖二等奖和1项全国教育硕士专业学位教学成果奖一等奖，获批2个国家特色专业、2门国家精品课程、3个教育部专业综合改革项目、4个教育部产学合作协同育人项目、1个全国教育硕士专业学位研究生联合培养示范基地，全力打造赣南及周边地区基础教育师资培养培训中心、研究咨询中心和改革发展服务中心，形成了以教师教育和文理学科为特色、文理管工多学科协调发展的办学格局。 学校始终坚持提高质量的办学宗旨，为国家和社会培养输送了近16万名毕业生。近五年，在校学生参加省级以上各类竞赛屡获大奖，其中荣获中宣部“五个一工程”奖、中国戏剧“梅花奖”、国际大学生数学建模竞赛一等奖、全国大学生创业大赛一等奖、全国大学生艺术展演一等奖、全国师范院校师范生教学技能大赛特等奖等竞赛一等奖190余人次；</td>\r\n");
      out.write("\t\t\t<td id=\"zs5\">zy.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs6\">byz.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs7\">赣南师范大学</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<label title=\"修改信息\"> \r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg1\" href=\"javascript:void(0)\" onclick=\"$('#dlg').dialog('open')\">\r\n");
      out.write("\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/png/xg.png\" style=\"width:15px;height:15px;\" />\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t修改\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t<label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\">\r\n");
      out.write("\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/png/sc.png\" style=\"width:15px;height:15px;\" />\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t删除\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
