/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-09-18 12:44:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_005fzhikao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../js/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../js/jquery-easyui-1.5.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../js/jquery-easyui-1.5.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../js/jquery-easyui-1.5.2/jquery.easyui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../js/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tt\").datagrid({\r\n");
      out.write("\t\turl : 'ListStudent2',\r\n");
      out.write("\t\tstriped : true,\r\n");
      out.write("\t\trownumbers: true,\r\n");
      out.write("\t\tidField : \"id\",\r\n");
      out.write(" \t\tpagination : true,\r\n");
      out.write("\t\tpageSize : 10,\r\n");
      out.write("\t\tpageList : [ 10, 20, 30 ,40],\r\n");
      out.write(" \t\tfitColumns : true,\r\n");
      out.write(" \t\tShowHeader :true,\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tBorderWidth:true,\r\n");
      out.write("\r\n");
      out.write("\t\tsortName : \"r_id\",\r\n");
      out.write(" \t\ttoolbar:\"#toolbar\",\r\n");
      out.write("\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tonLoadSuccess:function(data){    \r\n");
      out.write("\t        $(\"a[name='opera']\").linkbutton({text:'修改',plain:true,iconCls:'icon-edit'});\r\n");
      out.write("\t        $(\"a[name='oo']\").linkbutton({text:'删除',plain:true,iconCls:'icon-remove'});  \r\n");
      out.write("\t}, \r\n");
      out.write("\t\t columns : [ [ {\r\n");
      out.write("\t\t\tfield : 's_id',\r\n");
      out.write("\t\t\ttitle : '学生编号',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 's_name',\r\n");
      out.write("\t\t\ttitle : '学生姓名',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 's_teacher',\r\n");
      out.write("\t\t\ttitle : '老师姓名',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 's_phone',\r\n");
      out.write("\t\t\ttitle : '手机号码',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\tfield :  's_type',\r\n");
      out.write("\t\t\ttitle : '报名类型',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true,\r\n");
      out.write("\t\t\tformatter:function(value, row, index){ \r\n");
      out.write("\t\t\t\tif(value==2){\r\n");
      out.write("\t\t\t\t\treturn '艺考';\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\treturn '';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\tfield : 's_content',\r\n");
      out.write("\t\t\ttitle : '学习内容',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\tfield : 's_date',\r\n");
      out.write("\t\t\ttitle : '报名日期',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\tsortable : true\r\n");
      out.write("\t\t},{\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfield:'operate',title:'操作',align:'center', width:$(this).width()*0.1,  \r\n");
      out.write("\r\n");
      out.write("\t\t\tformatter:function(value, row, index){ \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t        var str = '<a href=\"#\" name=\"opera\" onclick=\"editUser('+index+')\" id=\"xg\" class=\"easyui-linkbutton\" ></a>';  \r\n");
      out.write("\t\t        var ss = '<a href=\"#\" name=\"oo\" onclick=\"editUsers('+index+')\" class=\"easyui-linkbutton\" ></a>';\r\n");
      out.write("\t\t        return str+ss;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}, ] ]\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function editUsers(index){\r\n");
      out.write("\t\r\n");
      out.write("\t$('#tt').datagrid('selectRow',index);// 关键在这里\r\n");
      out.write("\tvar row = $('#tt').datagrid('getSelected');\r\n");
      out.write("\t//alert('ID:'+row.r_id+\" 学校名称:\"+row.a_school);\r\n");
      out.write("\t//alert(row.s_id);\r\n");
      out.write("\twindow.location.href=\"StudentDelete.action?s_id=\"+row.s_id;\r\n");
      out.write("}\r\n");
      out.write("function editUser(index){\r\n");
      out.write("\t\r\n");
      out.write("\t$('#tt').datagrid('selectRow',index);// 关键在这里\r\n");
      out.write("\tvar row = $('#tt').datagrid('getSelected');\r\n");
      out.write("\t//alert('ID:'+row.r_id+\" 学校名称:\"+row.a_school);\r\n");
      out.write("\t//alert(row.s_phone);\r\n");
      out.write("\t//swindow.location.href=\"NoticeDel.action?n_id=\"+row.n_id;\r\n");
      out.write("\r\n");
      out.write("\t$(\"#s_id\").val(row.s_id);\r\n");
      out.write("\t$(\"#s_date\").val(row.s_date);\r\n");
      out.write("\t$(\"#s_name\").val(row.s_name);\r\n");
      out.write("\t$(\"#s_phone\").val(row.s_phone);\r\n");
      out.write("\t$(\"#s_content\").val(row.s_content);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tcache:true,\r\n");
      out.write("\t\tasync:true,\r\n");
      out.write("\t\turl:'Zhikao_UserAndList',\r\n");
      out.write("\t\ttype:'post',\r\n");
      out.write("\t\tdataType:'json',\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write(" \t\t\t $.each( data, function(index, content)\r\n");
      out.write("\t\t\t {  \r\n");
      out.write("\t\t\t  $(\"#sers\").append(\"<option value='\" + content.emp_id + \"'>\" + content.emp_name + \"</option>\");\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},error:function(){\r\n");
      out.write("\t\t\talert('服务繁忙！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t//对话框显示\r\n");
      out.write("\t\t\t$('#dd').dialog({\r\n");
      out.write("\t \t\t    title: 'My Dialog',\r\n");
      out.write("\t \t\t    width: 600,\r\n");
      out.write("\t \t\t    height: 300,\r\n");
      out.write("\t \t\t    closed: false,\r\n");
      out.write("\t \t\t    cache: false,\r\n");
      out.write("\t \t\t    //href: 'get_content.php',\r\n");
      out.write("\t \t\t    modal: true\r\n");
      out.write("\t \t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//增加\r\n");
      out.write("function zhikaoadd(){\r\n");
      out.write("\t//对话框显示\r\n");
      out.write("\t$('#dd2').dialog({\r\n");
      out.write("\t\t    title: 'My Dialog',\r\n");
      out.write("\t\t    width: 600,\r\n");
      out.write("\t\t    height: 300,\r\n");
      out.write("\t\t    closed: false,\r\n");
      out.write("\t\t    cache: false,\r\n");
      out.write("\t\t    //href: 'get_content.php',\r\n");
      out.write("\t\t    modal: true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t//给下拉框赋值\r\n");
      out.write("\t$(\"#add\").click(function(){\r\n");
      out.write("\t\talert(\"pppppppp\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\tcache:true,\r\n");
      out.write("\t\t\tasync:true,\r\n");
      out.write("\t\t\turl:'Zhikao_UserAndList',\r\n");
      out.write("\t\t\ttype:'post',\r\n");
      out.write("\t\t\tdataType:'json',\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t \t\t\t \r\n");
      out.write("\t \t\t\t $.each( data, function(index, content)\r\n");
      out.write("    \t\t\t {  \r\n");
      out.write("    \t\t\t  $(\"#tea\").append(\"<option value='\" + content.emp_id + \"'>\" + content.emp_name + \"</option>\");\r\n");
      out.write("    \t\t\t });\r\n");
      out.write("\t\t\t},error:function(){\r\n");
      out.write("\t\t\t\talert('服务繁忙！');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"dd\" style=\"display: none\"\r\n");
      out.write("data-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'添加',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t document.getElementById('add_form').submit(); \r\n");
      out.write("\t\t\t\t\t//\twindow.location.href='student_zhikao.jsp';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-no',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#dd').dialog('close');  //关闭添加窗口\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\"\r\n");
      out.write(">\r\n");
      out.write("<form action=\"StudentUpdate\" method=\"post\" id=\"add_form\">\r\n");
      out.write("<!-- <from action=\"Finance_save\"  method=\"post\"> -->\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" id=\"s_id\" name=\"student.s_id\" style=\"display: none\">\r\n");
      out.write("<input type=\"text\" id=\"s_type\" value=\"2\" name=\"student.s_type\" style=\"display: none\">\r\n");
      out.write("<tr><td>学生姓名</td><td><input type=\"text\" id=\"s_name\" name=\"student.s_name\"></td></tr>\r\n");
      out.write("<tr><td>老师姓名</td><td>\r\n");
      out.write("<!-- <input type=\"text\" id=\"s_teacher\" name=\"student.emp_id\"> -->\r\n");
      out.write("<select name=\"student.emp_id\" runat=\"server\" id=\"sers\"></select>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>手机号码</td><td><input type=\"text\" id=\"s_phone\" name=\"student.s_phone\"></td></tr>\r\n");
      out.write("<tr><td>学习内容</td><td><input type=\"text\" id=\"s_content\" name=\"student.s_content\"></td></tr>\r\n");
      out.write("<tr><td>时间</td><td><input type=\"text\" id=\"s_date\" name=\"student.s_date\" ></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!-- </from> -->\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 添加 -->\r\n");
      out.write("<div id=\"dd2\" style=\"display: none\"\r\n");
      out.write("data-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'添加',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t document.getElementById('add_forms').submit(); \r\n");
      out.write("\t\t\t\t\t\t//window.location.href='student_zhikao.jsp';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-no',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#dd2').dialog('close');  //关闭添加窗口\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\"\r\n");
      out.write(">\r\n");
      out.write("<form action=\"Student_Save\" method=\"post\" id=\"add_forms\">\r\n");
      out.write("<!-- <from action=\"Finance_save\"  method=\"post\"> -->\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("<input type=\"text\" id=\"s_name\" value=\"2\" name=\"student.s_type\" style=\"display: none\">\r\n");
      out.write("<tr><td>学生姓名</td><td><input type=\"text\" id=\"s_name\" name=\"student.s_name\"></td></tr>\r\n");
      out.write("<tr><td>身份证号</td><td><input type=\"text\" id=\"s_teacher\" name=\"student.id_number\"></td></tr>\r\n");
      out.write("<tr><td>老师姓名</td><td>\r\n");
      out.write("<select name=\"student.emp_id\" runat=\"server\" id=\"tea\">\r\n");
      out.write("<!-- <option value=\"1\">涂梅城</option> -->\r\n");
      out.write("<!-- <option value=\"2\">jhg</option> -->\r\n");
      out.write("<!-- <option value=\"3\">方法</option> -->\r\n");
      out.write("</select>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>手机号码</td><td><input type=\"text\" id=\"s_phone\" name=\"student.s_phone\"></td></tr>\r\n");
      out.write("<tr><td>学习内容</td><td><input type=\"text\" id=\"s_content\" name=\"student.s_content\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!-- </from> -->\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"easyui-tabs\" fit=\"true\" >\r\n");
      out.write("<div style=\"display:none\">\r\n");
      out.write("<!-- <table id=\"tt\" class=\"easyui-datagrid\">  -->\r\n");
      out.write("\r\n");
      out.write("<table id=\"tt\" class=\"easyui-datagrid\" iconCls=\"icon-save\" pagination=\"true\"></table>\r\n");
      out.write("<!-- </table> -->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"toolbar\">\r\n");
      out.write("\t<a href=\"#\" id=\"add\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\" onclick=\"zhikaoadd();\">增加</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
