/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-09-21 06:45:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stuLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.15.1.jar", Long.valueOf(1505974453894L));
    _jspx_dependants.put("jar:file:/E:/test/qf2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QingFeng/WEB-INF/lib/struts2-core-2.3.15.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1373806914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../js/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../js/jquery-easyui-1.5.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../js/jquery-easyui-1.5.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../js/jquery-easyui-1.5.2/jquery.easyui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../js/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"../images/logo/logo2.ico\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/image_body.css\" />\r\n");
      out.write("\r\n");
      out.write("<title>学生登录</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\t/* background-image: url(images/bj.jpg); */\r\n");
      out.write("\t/* background-size:contain; */\r\n");
      out.write("\t/* background-origin:content-box; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bj {\r\n");
      out.write("\t/* background-repeat: round; */\r\n");
      out.write("\t/* width:100%;\r\n");
      out.write("\theight:100%; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qj {\r\n");
      out.write("\tmargin-top: 10%;\r\n");
      out.write("\tmargin-left: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".la {\r\n");
      out.write("\ttop: 20px;\r\n");
      out.write("\tfloat: center;\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tborder-color: #000;\r\n");
      out.write("\tword-spacing: normal;\r\n");
      out.write("\tfont-family: '宋体';\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bu {\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tfont-family: '楷体';\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground: rgba(26, 228, 108, 0.52);\r\n");
      out.write("\tborder: 0 solid;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bu:hover {\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".di {\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\talign: center;\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bs {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: 1px solid #0492d6;\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.3);\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\twidth: 55px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p {\r\n");
      out.write("\talign: center;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground: rgba(233, 233, 233, 0.2);\r\n");
      out.write("\tpadding-top: 18px;\r\n");
      out.write("\tpadding-left: 35px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .bs {\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("} */\r\n");
      out.write(".ff {\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tpadding-bottom: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid #0492d6;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te_s {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid #0492d6;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te_y {\r\n");
      out.write("\twidth: 130px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid #0492d6;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te:focus {\r\n");
      out.write("\tborder: 1px solid rgba(4, 146, 214, 0.28);\r\n");
      out.write("\tbox-shadow: 1px 1px 3px rgba(4, 146, 214, 0.28), 0 1px 2px\r\n");
      out.write("\t\trgba(4, 146, 214, 0.28) inset;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("\t-moz-transition: padding .25s;\r\n");
      out.write("\t-webkit-transition: padding .25s;\r\n");
      out.write("\t-o-transition: padding .25s;\r\n");
      out.write("\ttransition: padding .25s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te_s:focus {\r\n");
      out.write("\tborder: 1px solid rgba(4, 146, 214, 0.28);\r\n");
      out.write("\tbox-shadow: 1px 1px 3px rgba(4, 146, 214, 0.28), 0 1px 2px\r\n");
      out.write("\t\trgba(4, 146, 214, 0.28) inset;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("\t-moz-transition: padding .25s;\r\n");
      out.write("\t-webkit-transition: padding .25s;\r\n");
      out.write("\t-o-transition: padding .25s;\r\n");
      out.write("\ttransition: padding .25s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te_y:focus {\r\n");
      out.write("\tborder: 1px solid rgba(4, 146, 214, 0.28);\r\n");
      out.write("\tbox-shadow: 1px 1px 3px rgba(4, 146, 214, 0.28), 0 1px 2px\r\n");
      out.write("\t\trgba(4, 146, 214, 0.28) inset;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("\t-moz-transition: padding .25s;\r\n");
      out.write("\t-webkit-transition: padding .25s;\r\n");
      out.write("\t-o-transition: padding .25s;\r\n");
      out.write("\ttransition: padding .25s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te:hover {\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te_s:hover {\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".te_y:hover {\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".m {\r\n");
      out.write("\twidth: 130px;\r\n");
      out.write("\theight: 39px;\r\n");
      out.write("\ttop: 3px;\r\n");
      out.write("\tborder-top: 5px;\r\n");
      out.write("\tborder-left: 2px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid #0492d6;\r\n");
      out.write("\tpadding-left: 5px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\t/* font-color:#fff; */\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("option {\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tfont-family: '楷体';\r\n");
      out.write("\tfont-size: auto;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twhite-space: pre;\r\n");
      out.write("\tmin-height: 1.2em;\r\n");
      out.write("\tpadding: 0px 2px 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".m:hover {\r\n");
      out.write("\t/* letter-spacing: 0px; */\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".t {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tmargin-top: 3px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\tfont-family: '楷体';\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".xl {\r\n");
      out.write("\tborder: 1;\r\n");
      out.write("\tborder-color: #233;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tfont-family: '楷体';\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".xl:hover {\r\n");
      out.write("\tletter-spacing: 1px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	String emp_id = request.getParameter("emp_id");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t//填写完姓名时验证\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction sname_test(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/*-----------------------验证码------------------*/\r\n");
      out.write("\t\t\t\tte_y = \"\";\r\n");
      out.write("\t\t\t\tvar cd = 4;\r\n");
      out.write("\t\t\t\tvar yzm = document.getElementById(\"s_phone\");\r\n");
      out.write("\t\t\t\tvar yzsz = new Array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd',\r\n");
      out.write("\t\t\t\t\t\t'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',\r\n");
      out.write("\t\t\t\t\t\t'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B',\r\n");
      out.write("\t\t\t\t\t\t'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',\r\n");
      out.write("\t\t\t\t\t\t'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < cd; i++) {\r\n");
      out.write("\t\t\t\t\tvar n = Math.floor(Math.random() * 52);\r\n");
      out.write("\t\t\t\t\tte_y += yzsz[n];\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (yzm) {\r\n");
      out.write("\t\t\t\t\tyzm.className = \"te_y\";\r\n");
      out.write("\t\t\t\t\tyzm.innerHTML = te_y;\r\n");
      out.write("\t\t\t\t\t//alert(te_y);\r\n");
      out.write("\t\t\t\t\t$(\"#sjm\").innerHTML=te_y;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t/*----------------------------------------------*/\r\n");
      out.write("\t\t\t\t$(\"#yz\").click(function(){\r\n");
      out.write("\t\t\t\t\t//setTimeout(function(){});\r\n");
      out.write("\t\t\t\t\t$(\"#yz\").attr(\"disabled\",\"\");\r\n");
      out.write("\t\t\t\t\tjs(60);\r\n");
      out.write("\t\t\t\t\t//alert(\"TTT\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar s_name = $('#s_name').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\tasync : true,\r\n");
      out.write("\t\t\t\t\tcache : true,\r\n");
      out.write("\t\t\t\t\turl : 'Find_stu.action',\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t's_name' : s_name,\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tif(data == '账户名不存在'){\r\n");
      out.write("\t\t\t\t\t\t\t document.getElementById(\"fon\").style.fontSize=\"10px\";\r\n");
      out.write("\t\t\t\t\t\t\t$('#fon').html(\"&nbsp;&nbsp;&nbsp;注册名不存在\");\r\n");
      out.write("\t\t\t\t\t\t\t$('#fon2').html('');\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"fon\").style.color=\"red\"; \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tsphone_test();\r\n");
      out.write("\t\t\t\t\t\t}else{    //账号存在\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"fon\").style.color=\"green\";\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"fon\").style.fontSize=\"20px\";\r\n");
      out.write("\t\t\t\t\t\t\t$('#fon').html(\"&nbsp;&nbsp;&nbsp;✔\");\r\n");
      out.write("\t\t\t\t\t\t\tsphone_test();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(XMLHttpRequest, textStatus) {\r\n");
      out.write("\t\t\t\t\t\talert(\"系统繁忙,请稍候再试!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction js(s){\r\n");
      out.write("\t\t\t\tif(s <= 0){\r\n");
      out.write("\t\t\t\t\t$(\"#yz\").val(\"重新获取\");\r\n");
      out.write("\t\t\t\t\t$(\"#yz\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#yz\").val(s+\"秒后重新获取\");\r\n");
      out.write("\t\t\t\tsetTimeout(\"js(\"+(s-1)+\")\",1000);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//填写完手机号码时验证\r\n");
      out.write("\tfunction sphone_test(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar s_name = $('#s_name').val();\r\n");
      out.write("\t\tvar s_phone = $('#s_phone').val();\r\n");
      out.write("\t\talert(\"FFYFY\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tcache : true,\r\n");
      out.write("\t\t\turl : 'Find_sphone.action',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t's_name' : s_name,\r\n");
      out.write("\t\t\t\t's_phone' : s_phone,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tif(data == '✔'){    //账号手机都正确\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"fon2\").style.color=\"green\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"fon2\").style.fontSize=\"20px\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#fon2').html(\"&nbsp;&nbsp;&nbsp;✔\");\r\n");
      out.write("\t\t\t\t\t$(\"#yz\").attr(\"disabled\", \"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//js(60);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\talert(\"验证码？\"+te_y);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\tasync : true,\r\n");
      out.write("\t\t\t\t\t\tcache : true,\r\n");
      out.write("\t\t\t\t\t\turl : 'yzm.action',\r\n");
      out.write("\t\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t's_phone' : s_phone,\r\n");
      out.write("\t\t\t\t\t\t\t'te_y' :te_y\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\talter(\"成功向\"+s_phone+\"发送验证码！\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function(XMLHttpRequest, textStatus) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"系统繁忙,请稍候再试!\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"fon2\").style.color=\"red\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"fon2\").style.fontSize=\"10px\";\r\n");
      out.write("\t\t\t\t\t$('#fon2').html(\"&nbsp;&nbsp;&nbsp;\"+data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(XMLHttpRequest, textStatus) {\r\n");
      out.write("\t\t\t\talert(\"系统繁忙,请稍候再试!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//保存登录学生\r\n");
      out.write("\t\tfunction submittest(){\r\n");
      out.write("\t\t\talert($(\"#sjm\").val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(te_y== $(\"#sjm\").val()){\r\n");
      out.write("\t\t\t\tvar a = document.getElementById(\"fon\").innerHTML;\r\n");
      out.write("\t\t\t\tvar b = document.getElementById(\"fon2\").innerHTML;\r\n");
      out.write("\t\t\t\tif(a == '&nbsp;&nbsp;&nbsp;✔' && b == '&nbsp;&nbsp;&nbsp;✔'){   //全部验证通过\r\n");
      out.write("\t\t\t\t\t//提交form表单\r\n");
      out.write("\t\t\t\t\tdocument.stuLogin.submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"验证码错误！\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"stuLogin\" action=\"StuLogin\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"bj\">\r\n");
      out.write("\t\t\t<div class=\"qj\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label class=\"t\">姓名：</label><input type=\"text\" id=\"s_name\"\r\n");
      out.write("\t\t\t\t\t\tname=\"student.s_name\" class=\"te\" /><font id=\"fon\">&nbsp;&nbsp;</font>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label class=\"t\">预留手机号：</label><input type=\"text\" id=\"s_phone\"\r\n");
      out.write("\t\t\t\t\t\tname=\"student.s_phone\" class=\"te\" /> <input class=\"m\" id=\"yz\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"获取验证码\" onclick=\"sname_test()\" /><font\r\n");
      out.write("\t\t\t\t\t\tid=\"fon2\">&nbsp;&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t<!-- <a onclick=\"yzm()\">GGGG</a> -->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label class=\"t\">手机验证码：</label><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"te_y\" id=\"sjm\" title=\"\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<label class=\"t\"></label><input type=\"button\" value=\"查询缴费\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"bu\" onclick=\"submittest()\" />\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
