/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-09-21 06:46:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>&nbsp;清风教育网 - 关于我们</title>\r\n");
      out.write("<link rel=\"icon\" href=\"images/logo/logo2.ico\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aboutus/all.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aboutus/text.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/jquery.mins.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/aboutus/aboutus1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/aboutus/aboutus2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"portfolio\" class=\"sel_portfolio\">\r\n");
      out.write("<br />\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"main\" style=\"\">\r\n");
      out.write("\t\t\t<!--ps_box-->\r\n");
      out.write("\t\t\t<div class=\"ps_box\">\r\n");
      out.write("\t\t\t\t<div class=\"pics_switch\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pb\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pic_banner_001\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pic_banner_002\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pic_banner_003\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic_box\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"pic_banner_004\" target=\"_blank\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"viewArrows prev\">上一张</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"viewArrows next\">下一张</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"pics_switch_clients\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"li_1\"><span class=\"current\">1</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"li_2\"><span>2</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"li_3\"><span>3</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"li_4\"><span>4</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--case_box-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<h2 style=\"font-size: 34px; font-family: '楷体';float:left;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<h2 style=\"font-size: 34px; font-family: '楷体';float:right;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h2 style=\"font-size: 34px; font-family: '楷体';width:70%;position: absolute;left:18%;\">\r\n");
      out.write("\t\t\t<font style=\"float:left;font-size:34px;\">\r\n");
      out.write("\t\t\t\t<a href=\"ncb.jsp\" title=\"点击查看-认证\" target=\"_blank\">权威认证</a>\r\n");
      out.write("\t\t\t</font>\r\n");
      out.write("\t\t\t发展历程\r\n");
      out.write("\t\t\t<font style=\"float:right;font-size:34px;\">\r\n");
      out.write("\t\t\t\t<a target=\"_blank\" title=\"点击查看-团队\" href=\"group.jsp\">关于团队</a>\r\n");
      out.write("\t\t\t</font>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<div style=\"*display: inline;*zoom: 1;\">\r\n");
      out.write("\t\t\t<div style=\"width:auto;float:center;padding-left:90px;\">\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\t<div class=\"event_wrap clearfix\" style=\"top:128%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"middle_line\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/aboutus/jquery.eventFlow.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar bigEvent = [ {\r\n");
      out.write("\t\t\t'year' : '8月份',\r\n");
      out.write("\t\t\t'events' : [ {\r\n");
      out.write("\t\t\t\t'mouths' : 2,\r\n");
      out.write("\t\t\t\t'times' : '2017年8月11日',\r\n");
      out.write("\t\t\t\t'even' : '项目正式启动，制作进入第一阶段，成立开发团队'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t'mouths' : 4,\r\n");
      out.write("\t\t\t\t'times' : '2017年8月22日',\r\n");
      out.write("\t\t\t\t'even' : '修改项目需求，制作进入第二阶段'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t'mouths' : 10,\r\n");
      out.write("\t\t\t\t'times' : '2017年8月25日',\r\n");
      out.write("\t\t\t\t'even' : '进行了项目启动之后最大的一次更新，修改及新增了easyUI官方文档，扩展部分功能组件'\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\t'year' : '9月份',\r\n");
      out.write("\t\t\t'events' : [ {\r\n");
      out.write("\t\t\t\t'mouths' : 2,\r\n");
      out.write("\t\t\t\t'times' : '2017年8月31日',\r\n");
      out.write("\t\t\t\t'even' : '项目合并，准备进入第三阶段开发'\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t'mouths' : 4,\r\n");
      out.write("\t\t\t\t'times' : '2017年9月3日',\r\n");
      out.write("\t\t\t\t'even' : '项目正式投入运营'\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t} ];\r\n");
      out.write("\t\t$('.event_wrap').eventFlow({\r\n");
      out.write("\t\t\t'events' : bigEvent\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
