/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-09-18 12:00:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cwbb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>&nbsp;清风教育网 - 财务报表管理</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"script/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/image_body.css\" />\r\n");
      out.write("<link type=\"text/css\" href=\"css/finance/style.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../script/finance/modernizr.js\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/echarts.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html, body {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding: 0 auto;\r\n");
      out.write("\tfont-family: \"Times New Roman\", arial, Verdana;\r\n");
      out.write("\tcolor: #817a53;\r\n");
      out.write("\tbackground: #fffffe;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\tasync : true,\r\n");
      out.write("\t\tcache : true,\r\n");
      out.write("\t\turl : 'GetBaoBiao.action',\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\tdata : {\r\n");
      out.write("\t\t\t'id' : 25,\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("/////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar arr = new Array();\r\n");
      out.write("\t\t\t$.each(data.stpList, function(index, content) {\r\n");
      out.write("\t\t\t\tarr[index] = content.value;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t// 基于准备好的dom，初始化echarts实例\r\n");
      out.write("\t\t\tvar myChart = echarts.init(document.getElementById('main'));\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar myDergi = echarts.init(document.getElementById('ddd'));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar zfpay = echarts.init(document.getElementById('zfpay'));\r\n");
      out.write("\t\t\t// 指定图表的配置项和数据\r\n");
      out.write("\t\t\tvar dss = {\r\n");
      out.write("\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\ttext : '缴费报表'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttooltip : {},\r\n");
      out.write("\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\tdata : [ '增长' ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\txAxis : {\r\n");
      out.write("\t\t\t\t\tdata : [ \"成考缴费\", \"艺考缴费\", \"会计缴费\", \"国家大学缴费\", \"远程教育缴费\" ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tyAxis : {},\r\n");
      out.write("\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\tname : '数值',\r\n");
      out.write("\t\t\t\t\ttype : 'bar',\r\n");
      out.write("\t\t\t\t\tdata : data.bb\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar pay = {\r\n");
      out.write("\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\ttext : '支付统计'\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\ttooltip : {},\r\n");
      out.write("\t\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\t\tdata : [ '增长' ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\txAxis : {\r\n");
      out.write("\t\t\t\t\t\tdata : [ \"支付宝\", \"微信\", \"银行转账\", \"现金\" ]\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tyAxis : {},\r\n");
      out.write("\t\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\t\tname : '数值',\r\n");
      out.write("\t\t\t\t\t\ttype : 'bar',\r\n");
      out.write("\t\t\t\t\t\tdata : data.zfpay\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar option = {\r\n");
      out.write("\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\ttext : '报名报表',\r\n");
      out.write("\t\t\t\t\tsubtext : '纯属虚构',\r\n");
      out.write("\t\t\t\t\tx : 'center'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttooltip : {\r\n");
      out.write("\t\t\t\t\ttrigger : 'item',\r\n");
      out.write("\t\t\t\t\tformatter : \"{a} <br/>{b} : {c} ({d}%)\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\torient : 'vertical',\r\n");
      out.write("\t\t\t\t\tleft : 'right',\r\n");
      out.write("\t\t\t\t\tdata : [ '成人高考', '艺考', '远程教育', '会计', '国家大学' ]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\tname : '访问来源',\r\n");
      out.write("\t\t\t\t\ttype : 'pie',\r\n");
      out.write("\t\t\t\t\tradius : '55%',\r\n");
      out.write("\t\t\t\t\tcenter : [ '50%', '60%' ],\r\n");
      out.write("\t\t\t\t\tdata : [{ \"name\" : \"成人高考\",\r\n");
      out.write("\t\t\t\t\t\t\"value\" : arr[0] },{ \"name\" : \"艺考\",\r\n");
      out.write("\t\t\t\t\t\t\t\"value\" :  2 },{ \"name\" : \"远程教育\",\r\n");
      out.write("\t\t\t\t\t\t\t\"value\" :  4 },{ \"name\" : \"会计\",\r\n");
      out.write("\t\t\t\t\t\t\t\"value\" : 1 },{ \"name\" : \"国家大学\",\r\n");
      out.write("\t\t\t\t\t\t\t\"value\" :  1 }] ,\r\n");
      out.write("\t\t\t\t\titemStyle : {\r\n");
      out.write("\t\t\t\t\t\temphasis : {\r\n");
      out.write("\t\t\t\t\t\t\tshadowBlur : 10,\r\n");
      out.write("\t\t\t\t\t\t\tshadowOffsetX : 0,\r\n");
      out.write("\t\t\t\t\t\t\tshadowColor : 'rgba(0, 0, 0, 0.5)'\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 使用刚指定的配置项和数据显示图表。\r\n");
      out.write("\t\t\tmyChart.setOption(option);\r\n");
      out.write("\t\t\tzfpay.setOption(pay);\r\n");
      out.write("\t\t\tmyDergi.setOption(dss);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(XMLHttpRequest, textStatus) {\r\n");
      out.write("\t\t\talert(\"系统繁忙,请稍候再试!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 为ECharts准备一个具备大小（宽高）的Dom -->\r\n");
      out.write("\t<div style=\"width: 100%; height: 100%;\">\r\n");
      out.write("\t\t<div id=\"main\"\r\n");
      out.write("\t\tstyle=\"width: 500px; height: 400px; float: right; position: initial; right: 10%; top: 110px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"ddd\"\r\n");
      out.write("\t\tstyle=\"width: 600px; height: 400px; float: left; position: initial; left: 2%; top: 110px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"zfpay\"\r\n");
      out.write("\t\tstyle=\"width: 400px; height: 400px; float: left; position: initial; left: 5%; top: 110px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
