/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-09-21 06:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class teamwork_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>&nbsp;清风教育网 - 合作/加盟</title>\r\n");
      out.write("<link rel=\"icon\" href=\"images/logo/logo2.ico\" />\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tbackground:#FFF0F5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article{\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\twidth:889px;\r\n");
      out.write("\t/*定义页面内容显示为3列*/\r\n");
      out.write("\t-webkit-column-count:4;\r\n");
      out.write("\t-moz-column-count:4;\r\n");
      out.write("\tcolumn-count:4;\r\n");
      out.write("\t/*定义列间距为3em，默认为1em*/\r\n");
      out.write("\t-webkit-column-gap:20px;\r\n");
      out.write("\t-moz-column-gap:20px;\r\n");
      out.write("\tcolumn-gap:20px;\r\n");
      out.write("\t/*定义列边框为2像素宽的灰色虚线*/\r\n");
      out.write("\t-webkit-column-rule:4px double #dfdfdf;\r\n");
      out.write("\t-moz-column-rule:4px double #dfdfdf;\r\n");
      out.write("\tcolumn-rule:4px double #dfdfdf;\r\n");
      out.write("\t/*设置各列高度自动调整*/\r\n");
      out.write("\t-webkit-column-fill:auto;\r\n");
      out.write("\t-moz-column-fill:auto;\r\n");
      out.write("\tcolumn-fill:auto;\r\n");
      out.write("\tbackground:url(images/article_bg.png) no-repeat bottom;/*底部*/\r\n");
      out.write("}\r\n");
      out.write("/*设置标题跨越所有列显示*/\r\n");
      out.write(".title{\r\n");
      out.write("\twidth:877px;\r\n");
      out.write("\theight:250px;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\tbackground:url(images/banner1.jpg) no-repeat 100% 100%;/*头部*/\r\n");
      out.write("\t-webkit-column-span:all;\r\n");
      out.write("\t-moz--column-span:all;\r\n");
      out.write("\tcolumn-span:all;\r\n");
      out.write("\tmargin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("h1{ \r\n");
      out.write("\tcolor:#F5FFFA;\r\n");
      out.write("\tmargin-right:125px;\r\n");
      out.write("\tfont-size:80px;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding:12px;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2{ \r\n");
      out.write("\tcolor:#00E0ED;\r\n");
      out.write("\twidth:20px;\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tmargin-top:100px;\r\n");
      out.write("\tfont-size:19px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tpadding:12px;\r\n");
      out.write("\tfont-weight:400;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p{\t\r\n");
      out.write("\tcolor:#333; \r\n");
      out.write("\tfont-size:14px; \r\n");
      out.write("\tline-height:180%; \r\n");
      out.write("\ttext-indent:2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor:#000;\r\n");
      out.write("}\r\n");
      out.write("a:visited{\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("\tcolor:#00FFFF;\r\n");
      out.write("}\r\n");
      out.write("a:active{\r\n");
      out.write("\tcolor:blue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"height:50px;font-size:35px;font-family:'楷体';margin-left:18%;\">\r\n");
      out.write("    \t<p>\r\n");
      out.write("    \t\t我们诚挚欢迎您的加入\r\n");
      out.write("    \t</p>\r\n");
      out.write("    \t\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"height:190px;font-size:25px;font-family:'楷体';margin-left:28%;\">\r\n");
      out.write("    \t<p style=\"float:right;position: absolute;right:46%;\">\r\n");
      out.write("    \t\t<a href=\"tencent://message/?uin=2644794564&Site=&Menu=yes\">\r\n");
      out.write("    \t\t\t<label style=\"margin-bottom:2px;position: absolute;bottom:55%;\"> QQ:</label>\r\n");
      out.write("    \t\t\t<img src=\"images/tb.png\" style=\"width:65px;height:75px;margin-left:30%;\" />\r\n");
      out.write("    \t\t</a>\r\n");
      out.write("    \t\t<br />\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<span style=\"height:10px;display:inline-block;\"></span>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<br />\r\n");
      out.write("    \t\t<label style=\"\">电话:666-6666-6666</label>\r\n");
      out.write("    \t</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<article>\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("            <h1>清风</h1>\r\n");
      out.write("            <h2>平台介绍</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"p\">盼望着，盼望着，东风来了，春天的脚步近了。</p>\r\n");
      out.write("        <p class=\"p\">一切都像刚睡醒的样子，欣欣然张开了眼。山朗润起来了，水涨起来了，太阳的脸红起来了。</p>\r\n");
      out.write("        <p class=\"p\">小草偷偷地从土里钻出来，嫩嫩的，绿绿的。园子里，田野里，瞧去，一大片一大片满是的。坐着，躺着，打两个滚，踢几脚球，赛几趟跑，捉几回迷藏。风轻悄悄的，草软绵绵的。\r\n");
      out.write("        <p class=\"p\">桃树、杏树、梨树，你不让我，我不让你，都开满了花赶趟儿。红的像火，粉的像霞，白的像雪。花里带着甜味儿；闭了眼，树上仿佛已经满是桃儿、杏儿、梨儿。花下成千成百的蜜蜂嗡嗡地闹着，大小的蝴蝶飞来飞去。野花遍地是：杂样儿，有名字的，没名字的，散在草丛里，像眼睛，像星星，还眨呀眨的。</p>\r\n");
      out.write("        <p class=\"p\">“吹面不寒杨柳风”，不错的，像母亲的手抚摸着你。风里带来些新翻的泥土的气息，混着青草味儿，还有各种花的香，都在微微润湿的空气里酝酿。鸟儿将巢安在繁花嫩叶当中，高兴起来了，呼朋引伴地卖弄清脆的喉咙，唱出婉转的曲子，跟轻风流水应和着。牛背上牧童的短笛，这时候也成天嘹亮地响着。</p>\r\n");
      out.write("        <p class=\"p\">雨是最寻常的，一下就是三两天。可别恼。看，像牛毛，像花针，像细丝，密密地斜织着，人家屋顶上全笼着一层薄烟。树叶儿却绿得发亮，小草儿也青得逼你的眼。傍晚时候，上灯了，一点点黄晕的光，烘托出一片安静而和平的夜。在乡下，小路上，石桥边，有撑起伞慢慢走着的人，地里还有工作的农民，披着蓑戴着笠。他们的房屋，稀稀疏疏的，在雨里静默着。</p>\r\n");
      out.write("    \t<p class=\"p\">天上风筝渐渐多了，地上孩子也多了。城里乡下，家家户户，老老小小，也赶趟儿似的，一个个都出来了。舒活舒活筋骨，抖擞抖擞精神，各做各的一份事去。“一年之计在于春”，刚起头儿，有的是工夫，有的是希望。</p>\r\n");
      out.write("        <p class=\"p\">春天像刚落地的娃娃，从头到脚都是新的，它生长着。</p>\r\n");
      out.write("        <p class=\"p\">春天像小姑娘，花枝招展的，笑着，走着。</p>\r\n");
      out.write("        <p class=\"p\">春天像健壮的青年，有铁一般的胳膊和腰脚，领着我们上前去。</p>\r\n");
      out.write("    </article>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
