/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-08-25 00:25:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class beanimage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"css/beanimage.css\" />\r\n");
      out.write("<title>首页轮播图管理中心</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#m1_i\").datagrid({\r\n");
      out.write("\t\t\turl:\"academy_list\",\r\n");
      out.write("\t\t\tstriped:true,\r\n");
      out.write("\t\t\tidField:\"id\",\r\n");
      out.write("\t\t\tpagination:true,\r\n");
      out.write("\t\t\tpagesize:10,\r\n");
      out.write("\t\t\tpageList : [ 10, 20, 30, 40 ],\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tsortName : \"id\",\r\n");
      out.write("\t\t\tsortOrder : \"desc\",\r\n");
      out.write("\t\t\tcolumns:[[\r\n");
      out.write("\t\t\t          {field:\"picture_one\",title:\"\"}\r\n");
      out.write("\t\t\t          ]]\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"script/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"script/jquery-easyui-1.5.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"script/jquery-easyui-1.5.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"script/jquery-easyui-1.5.2/jquery.easyui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"script/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 30px auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor: #F30;\r\n");
      out.write("\tfont-family: '楷体';\r\n");
      out.write("\tletter-spacing: 5px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-of-type(odd) {\r\n");
      out.write("\tbackground-color: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-of-type(even) {\r\n");
      out.write("\tbackground-color: #F2F2F2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:hover {\r\n");
      out.write("\tcolor: #F30;\r\n");
      out.write("\tbackground-color: #EFFEED;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:hover td:nth-child(1) {\r\n");
      out.write("\tbackground: url(images/tr-hover-bg.png) no-repeat 3px 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tborder-bottom: 1px solid #CCC;\r\n");
      out.write("\tborder-top: 1px solid #CCC;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tbackground-color: #F8F4DA;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder-bottom: 1px solid #CCC;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*定义列的宽度*/\r\n");
      out.write("[id^=\"Im\"] {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"ImTx\"] {\r\n");
      out.write("\twidth: 510px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"Gxw\"] {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"Xtt\"] {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"SetUp\"] {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dc {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"ld\"] {\r\n");
      out.write("\ttext-indent: 3px;\r\n");
      out.write("\tfont: \"楷体\";\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.1) no-repeat;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid gray;\r\n");
      out.write("\tletter-spacing: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ld:hover {\r\n");
      out.write("\tletter-spacing: 2px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("/* \r\n");
      out.write(".file {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background: #D0EEFF;\r\n");
      out.write("    border: 1px solid #99D3F5;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    padding: 4px 12px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    color: #1E88C7;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-indent: 0;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("    top:10px;\r\n");
      out.write("    font:\"楷体\";\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("}\r\n");
      out.write(".file input {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    font-size: 100px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("}\r\n");
      out.write(".file:hover {\r\n");
      out.write("    background: #AADFFD;\r\n");
      out.write("    border-color: #78C3F3;\r\n");
      out.write("    color: #004974;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("} */\r\n");
      out.write(".report-file {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    height: 28px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border: 1px solid #428bca;\r\n");
      out.write("    background: none repeat scroll 0 0 #428bca;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write(".report-file span {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: block;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("}\r\n");
      out.write(".file-prew {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left:0;\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    font-size: 100px; \r\n");
      out.write("    opacity: 0; \r\n");
      out.write("    filter: alpha(opacity=0);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("td:hover{\r\n");
      out.write("\ttext-overflow:inherit;\r\n");
      out.write("\toverflow:visible;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- \t\t\ticonCls: 'icon-save',\r\n");
      out.write("\t\t\t\ttoolbar: [{\r\n");
      out.write("\t\t\t\t\ttext:'Add',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-add',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('add')\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\t\ttext:'Save',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-save',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('save')\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}],\r\n");
      out.write(" -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar s = $(\"#m1_i\").text();\r\n");
      out.write("\tvar m = $(\"#m1_t\").text();\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//第一组图片和文字\r\n");
      out.write("\t\t$(\"#xg1\").click(function() {\r\n");
      out.write("\t\t\talert($(\"#m1_i\").text() + $(\"#m1_t\").text());\r\n");
      out.write("\t\t\ttextName.value = $(\"#m1_i\").text();\r\n");
      out.write("\t\t\tz.value = $(\"#m1_t\").text();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//第二组图片和文字\r\n");
      out.write("\t\t$(\"#xg2\").click(function(){\r\n");
      out.write("\t\t\talert($(\"#m2_i\").text()+\"---\"+$(\"#m2_t\").text());\r\n");
      out.write("\t\t\ttextName.value = $(\"#m2_i\").text();\r\n");
      out.write("\t\t\tz.value = $(\"#m2_t\").text();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//第三组图片和文字\r\n");
      out.write("\t\t$(\"#xg3\").click(function(){\r\n");
      out.write("\t\t\talert($(\"#m3_i\").text()+\"---\"+$(\"#m3_t\").text());\r\n");
      out.write("\t\t\ttextName.value = $(\"#m3_i\").text();\r\n");
      out.write("\t\t\tz.value = $(\"#m3_t\").text();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t/* \r\n");
      out.write("\t$(\".a-upload\").on(\"change\",\"input[type='file']\",function(){\r\n");
      out.write("\t    var filePath=$(this).val();\r\n");
      out.write("\t    if(filePath.indexOf(\"jpg\")!=-1 || filePath.indexOf(\"png\")!=-1){\r\n");
      out.write("\t        $(\".fileerrorTip\").html(\"\").hide();\r\n");
      out.write("\t        var arr=filePath.split('\\\\');\r\n");
      out.write("\t        var fileName=arr[arr.length-1];\r\n");
      out.write("\t        $(\".showFileName\").html(fileName);\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t        $(\".showFileName\").html(\"\");\r\n");
      out.write("\t        $(\".fileerrorTip\").html(\"您未上传文件，或者您上传文件类型有误！\").show();\r\n");
      out.write("\t        return false \r\n");
      out.write("\t    }\r\n");
      out.write("\t}); */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 直接点击删除操作时恢复被删除图文的初始数据 -->\r\n");
      out.write("\t<!-- 弹窗 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" title=\"修改\"\r\n");
      out.write("\t\tstyle=\"width: 80%; height: 400px; max-width: 800px; padding: 2px; display: none;\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'确定',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ok',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('ok');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\ticonCls:'fi-x',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('cancel');;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<textarea rows=\"10\" cols=\"20\" id=\"z\" style=\"width: 95%; height: 230px; font-size: 16px; border-radius: 5px; border: 0.2; color: red; background-color: rgba(0, 0, 0, .05)；font:'楷体';font-size:18px;\"></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>上传文件</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>首页轮播图管理</h1>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th id=\"Im\">图片</th>\r\n");
      out.write("\t\t\t<th id=\"ImTx\">图片配字</th>\r\n");
      out.write("\t\t\t<th id=\"SetUp\">操作</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"m1\">\r\n");
      out.write("\t\t\t<td id=\"m1_i\" width=\"300px;\">F:/Images/01.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"m1_t\" width=\"520px;\">这是首页第一张轮播图的搭配文字内容,这是首页第一张轮播图的搭配文字内容,这是首页第一张轮播图的搭配文字内容,这是首页第一张轮播图的搭配文字内容,这是首页第一张轮播图的搭配文字内容</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><label title=\"修改信息\"> <a type=\"radio\" name=\"st1\" class=\"role-easyui-linkbutton-edit l-btn l-btn-small l-btn-plain\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg1\" href=\"javascript:void(0)\" data-options=\"plain:true,iconCls:'fi-pencil icon-blue'\"\r\n");
      out.write("\t\t\t\t\tonclick=\"$('#dlg').dialog('open')\">修改</a></label> <label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc1\" href=\"\">删除</a>\r\n");
      out.write("\t\t\t</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th id=\"Im\">图片</th>\r\n");
      out.write("\t\t\t<th id=\"ImTx\">图片配字</th>\r\n");
      out.write("\t\t\t<th id=\"SetUp\">操作</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"m2\">\r\n");
      out.write("\t\t\t<td id=\"m2_i\" width=\"300px;\">F:/Images/02.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"m2_t\" width=\"520px;\">这是首页第二张轮播图的搭配文字内容</td>\r\n");
      out.write("\t\t\t<td><label title=\"修改信息\"> <a type=\"radio\" name=\"st1\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg2\" href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\tonclick=\"$('#dlg').dialog('open')\">修改</a></label> <label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc2\" href=\"\">删除</a>\r\n");
      out.write("\t\t\t</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th id=\"Im\">图片</th>\r\n");
      out.write("\t\t\t<th id=\"ImTx\">图片配字</th>\r\n");
      out.write("\t\t\t<th id=\"SetUp\">操作</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"m3\">\r\n");
      out.write("\t\t\t<td id=\"m3_i\" width=\"300px;\">F:/Images/03.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"m3_t\" width=\"520px;\">这是首页第三张轮播图的搭配文字内容</td>\r\n");
      out.write("\t\t\t<td><label title=\"修改信息\"> <a type=\"radio\" name=\"st1\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg3\" href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\tonclick=\"$('#dlg').dialog('open')\">修改</a></label> <label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc3\" href=\"\">删除</a>\r\n");
      out.write("\t\t\t</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
