/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-08-25 01:40:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.houtai;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class zhaosheng_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>招生简章</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../script/jquery-easyui-1.5.2/jquery.min.js\"></script>\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../script/jquery-easyui-1.5.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link id=\"easyuiTheme\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../script/jquery-easyui-1.5.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../script/jquery-easyui-1.5.2/jquery.easyui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"../script/jquery-easyui-1.5.2/locale/easyui-lang-zh_CN.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:30px auto;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\t\r\n");
      out.write("\tcolor:#666;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin:10px;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\tcolor:#F30;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("\tletter-spacing:5px;\r\n");
      out.write("\tfont-weight:600;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("\tfont-size:13px;\r\n");
      out.write("}\r\n");
      out.write("tr {\r\n");
      out.write("\theight:50px;\r\n");
      out.write("}\r\n");
      out.write("tr:nth-of-type(odd) {\r\n");
      out.write("\tbackground-color:#FFF;\r\n");
      out.write("}\r\n");
      out.write("tr:nth-of-type(even) {\r\n");
      out.write("\tbackground-color:#F2F2F2;\r\n");
      out.write("}\r\n");
      out.write("tr:hover {\r\n");
      out.write("\tcolor:#F30;\r\n");
      out.write("\tbackground-color:#EFFEED;\r\n");
      out.write("}\r\n");
      out.write("tr:hover td:nth-child(1){\r\n");
      out.write("\tbackground:url(images/tr-hover-bg.png) no-repeat 3px 8px;\r\n");
      out.write("}\r\n");
      out.write("th {\r\n");
      out.write("\tborder-bottom:1px solid #CCC;\r\n");
      out.write("\tborder-top:1px solid #CCC;\r\n");
      out.write("\tcolor:#333;\r\n");
      out.write("\tbackground-color:#F8F4DA;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("\tborder-bottom:1px solid #CCC;\r\n");
      out.write("}\r\n");
      out.write("/*定义列的宽度*/\r\n");
      out.write("[id^=\"Im\"] {\r\n");
      out.write("\twidth:500px;\r\n");
      out.write("}\r\n");
      out.write("[id=\"ImTx\"] {\r\n");
      out.write("\twidth:510px;\r\n");
      out.write("}\r\n");
      out.write("[id=\"Gxw\"] {\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write("[id=\"Xtt\"] {\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("[id=\"SetUp\"] {\r\n");
      out.write("\twidth:120px;\r\n");
      out.write("}\r\n");
      out.write(".dc{\r\n");
      out.write("\twidth:250px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("[id=\"ld\"] {\r\n");
      out.write("\ttext-indent:3px;\r\n");
      out.write("\tfont:\"楷体\";\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tbackground: rgba(255,255,255,0.1) no-repeat;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.5px solid gray;\r\n");
      out.write("\tletter-spacing:3px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#ld:hover{\r\n");
      out.write("\tletter-spacing:2px;\r\n");
      out.write("\tborder: 0.5px solid red;\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("\tbackground-color:rgba(255,255,255,0.5);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".la{\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tmargin:10px;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\tcolor:#F30;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("\tletter-spacing:5px;\r\n");
      out.write("\tfont-weight:600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ct{\r\n");
      out.write("\twidth:350px;\r\n");
      out.write("\theight:28px;\r\n");
      out.write("\tfont-size:24px;\r\n");
      out.write("\tfont-family:'楷体';\r\n");
      out.write("\tbackground:rgba(255,255,255,0.5); \r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tborder: 0.2; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cz{\r\n");
      out.write("\twidth: 95%; \r\n");
      out.write("\theight: 230px; \r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tfont-family:'楷体'; \r\n");
      out.write("\tborder-radius: 5px; \r\n");
      out.write("\tborder: 0.2; \r\n");
      out.write("\tcolor: red; \r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, .05);\r\n");
      out.write("\tfont:'楷体';\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("}\r\n");
      out.write(".report-file {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    height: 28px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border: 1px solid #428bca;\r\n");
      out.write("    background: none repeat scroll 0 0 #428bca;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write(".report-file span {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: block;\r\n");
      out.write("    line-height: 28px;\r\n");
      out.write("}\r\n");
      out.write(".file-prew {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left:0;\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    font-size: 100px; \r\n");
      out.write("    opacity: 0; \r\n");
      out.write("    filter: alpha(opacity=0);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("td:hover{\r\n");
      out.write("\ttext-overflow:inherit;\r\n");
      out.write("\toverflow:visible;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#xg1\").click(function(){\r\n");
      out.write("\t\t\ttextName1.value = $(\"#zs1\").text();\r\n");
      out.write("\t\t\ttextName2.value = $(\"#zs3\").text();\r\n");
      out.write("\t\t\ttextName3.value = $(\"#zs5\").text();\r\n");
      out.write("\t\t\ttextName4.value = $(\"#zs6\").text();\r\n");
      out.write("\t\t\tjj.value = $(\"#zs2\").text();\r\n");
      out.write("\t\t\tnr.value = $(\"#zs4\").text();\r\n");
      out.write("\t\t\tlx.value = $(\"#zs7\").text();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" title=\"修改\"\r\n");
      out.write("\t\tstyle=\"width: 80%; height: 400px; max-width: 800px; padding: 2px; display: none;\"\r\n");
      out.write("\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tclosed:true,\r\n");
      out.write("\t\t\t\tbuttons: [{\r\n");
      out.write("\t\t\t\t\ttext:'确定',\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-ok',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('ok');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttext:'取消',\r\n");
      out.write("\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\talert('cancel');;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}]\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>图标</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName1').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName1\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>院校图片</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName2').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName2\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>专业图片</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName3').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName3\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div class=\"report-file\">\r\n");
      out.write("\t\t\t      <span>毕业证图片</span>\r\n");
      out.write("\t\t\t      <input tabindex=\"3\" size=\"3\" name=\"report\" class=\"file-prew\" type=\"file\" onchange=\"document.getElementById('textName4').value=this.value\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"textName4\" style=\"height: 28px;border:1px solid #f1f1f1\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label class=\"la\">学校简介：</label><textarea rows=\"10\" cols=\"20\" id=\"jj\" class=\"cz\" ></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<label class=\"la\">介绍内容：</label><textarea rows=\"10\" cols=\"20\" id=\"nr\" class=\"cz\" ></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label class=\"la\">类型：</label><input type=\"text\" id=\"lx\" class=\"ct\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<h1>首页新闻管理</h1>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<th id=\"Gxw\">图标</th>\r\n");
      out.write("\t\t\t<th id=\"Gxw\">学校简介</th>\r\n");
      out.write("\t\t\t<th id=\"Gxw\">院校图片</th>\r\n");
      out.write("\t\t\t<th id=\"Gxw\">介绍内容</th>\r\n");
      out.write("\t\t\t<th id=\"Xtt\">专业图片</th>\r\n");
      out.write("\t\t\t<th id=\"Xtt\">毕业证图片</th>\r\n");
      out.write("\t\t\t<th id=\"Xtt\">类型</th>\r\n");
      out.write("\t\t\t<th id=\"SetUp\">操作</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td id=\"zs1\">s1.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs2\">北京外国语大学，简称北外，由中华人民共和国教育部直属，位列国家首批“211工程”，入选“985工程优势学科创新平台”、\"2011计划\"</td>\r\n");
      out.write("\t\t\t<td id=\"zs3\">school.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs4\">北京外国语大学（Beijing Foreign Studies University），简称北外，由中华人民共和国教育部直属，位列国家首批“211工程”，入选“985工程优势学科创新平台”、“2011计划”，为财政部6所“小规模试点高校“之一，国际大学翻译学院联合会成员，设有研究生院，是中国外国语类高等院校中历史悠久、教授语种最多、办学层次齐全的全国重点大学，被誉为“共和国外交官摇篮”。 北京外国语大学前身是1941年成立于延安的中国人民抗日军事政治大学三分校俄文大队，后发展为延安外国语学校，建校始隶属于中国共产党领导。新中国成立后，学校归外交部领导。1954年，更名为北京外国语学院；1959年，与北京俄语学院合并组建新的北京外国语学院。1980年后直属国家教育部领导。1994年，正式更名为北京外国语大学。</td>\r\n");
      out.write("\t\t\t<td id=\"zs5\">zy.png</td>\r\n");
      out.write("\t\t\t<td id=\"zs6\">byz.jpg</td>\r\n");
      out.write("\t\t\t<td id=\"zs7\">北京大学</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><label title=\"修改信息\"> <a type=\"radio\" name=\"st1\"\r\n");
      out.write("\t\t\t\t\tvalue=\"修改\" id=\"xg1\" href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\tonclick=\"$('#dlg').dialog('open')\">修改</a></label> <label title=\"恢复初始值\">\r\n");
      out.write("\t\t\t\t\t<a type=\"radio\" name=\"st1\" value=\"删除\" id=\"sc1\" href=\"\">删除</a>\r\n");
      out.write("\t\t\t</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
